#!/bin/bash
# Exercise 08: Real GitHub Pull Request
echo "--------------------------------------------------------"
echo "EXERCISE 08: THE COLLABORATION (REAL PULL REQUEST)"
echo "--------------------------------------------------------"
echo "A Pull Request (PR) is the standard way to contribute code"
echo "to open-source projects. You are going to make a real one now!"
echo ""
echo "PREREQUISITES:"
echo "1. You must have a GitHub account."
echo "2. You must have FORKED 'DevelSSN/twit' on GitHub."
echo ""
echo "STEPS TO FOLLOW:"
echo "1. Create a branch:      git checkout -b feat/my-contribution"
echo "2. Make a small change:  echo 'Your Name,Contributor' >> files/actors.csv"
echo "3. Commit it:            git add files/actors.csv"
echo "4.                       git commit -m 'J: my first pr'"
echo ""
echo "5. Add your fork as a remote (Replace YOUR_USERNAME):"
echo "   git remote add my-fork https://github.com/YOUR_USERNAME/twit.git"
echo ""
echo "6. Push to your fork:    git push -u my-fork feat/my-contribution"
echo ""
echo "7. Final Step: Go to https://github.com/DevelSSN/twit"
echo "   Click 'Compare & pull request' and title it: Example PR"
echo ""
echo "--------------------------------------------------------"
echo "Once you have opened the PR on the website, you are done!"
echo "--------------------------------------------------------"
