#!/bin/bash
# Exercise 00: Setup and Configuration
echo "--------------------------------------------------------"
echo "EXERCISE 00: PREPARING THE TOOLS"
echo "--------------------------------------------------------"
echo "Before you can snapshot code, you must identify yourself"
echo "to Git and ensure the tool is installed."
echo ""
echo "1. INSTALLATION CHECK:"
echo "   - Linux (Ubuntu/Debian): sudo apt install git"
echo "   - Linux (Fedora):        sudo dnf install git"
echo "   - WSL:                   (Same as Linux above)"
echo "   - macOS:                 brew install git (or xcode-select --install)"
echo "   - Windows:               Download from https://git-scm.com"
echo ""
echo "2. CONFIGURATION (COMMANDS TO RUN):"
echo "   git config --global user.name 'Your Name'"
echo "   git config --global user.email 'your@email.com'"
echo "   git config --global init.defaultBranch main"
echo ""
echo "3. VERIFY:"
echo "   git config --list"
echo ""
echo "Then run ./verify.sh"
echo "--------------------------------------------------------"
