#!/bin/bash
# Exercise 07: Remote Workflow
echo "--------------------------------------------------------"
echo "EXERCISE 07: THE SOCIAL NETWORK (REMOTES)"
echo "--------------------------------------------------------"
echo "Git is distributed, meaning you usually work with a 'remote'."
echo "Since we are working locally, we will simulate a remote by"
echo "creating a 'bare' clone of this repository in another folder."
echo ""
echo "COMMANDS TO RUN:"
echo "1. cd .. && git clone --bare twit twit-remote.git"
echo "   (This creates your 'server')"
echo "2. cd twit"
echo "3. git remote add origin ../twit-remote.git"
echo "4. git push -u origin main"
echo ""
echo "Now your local work is backed up in 'twit-remote.git'!"
echo "Then run ./verify.sh"
echo "--------------------------------------------------------"
